-- Schema v1: JSON snapshots are private; indexed keys enforce document scope.
CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY);
INSERT OR IGNORE INTO schema_versions VALUES(1);
CREATE TABLE IF NOT EXISTS policies(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS actors(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS links(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS grants(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS suggestions(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS publications(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS document_writes(id TEXT PRIMARY KEY, doc TEXT NOT NULL UNIQUE, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS requests(id TEXT PRIMARY KEY, doc TEXT NOT NULL, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, doc TEXT NOT NULL, suggestion_id TEXT, action TEXT NOT NULL CHECK(length(action)>0), json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS events_doc_seq ON events(doc,seq);
CREATE TRIGGER IF NOT EXISTS events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT,'immutable event'); END;
CREATE TRIGGER IF NOT EXISTS events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT,'immutable event'); END;
